coverage:
  status:
    project:
      default:
        informational: true
      backend:
        flags:
          - backend
        informational: true
      web:
        flags:
          - web
        informational: true
      mobile:
        flags:
          - mobile
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - apps/backend/.*
      carryforward: true
    - name: web
      paths:
        - apps/web/.*
      carryforward: true
    - name: mobile
      paths:
        - apps/mobile/.*
      carryforward: true
