variable "project_name" {
  type        = string
  description = "Short name used in resource tags and names."
}

variable "environment" {
  type        = string
  description = "Deployment stage (e.g. minimo, experimentos)."
}

variable "private_data_subnet_ids" {
  type        = list(string)
  description = "Private data subnets (one per AZ) used for the cache subnet group."
}

variable "security_group_ids" {
  type        = list(string)
  description = "Security group ids for the replication group (typically the Redis tier SG from the security_groups module)."
}

variable "node_type" {
  type        = string
  description = "Cache node instance type."
  default     = "cache.t4g.medium"
}

variable "num_cache_clusters" {
  type        = number
  description = "Number of cache clusters (nodes) in the replication group, including the primary. Ignored when cluster_mode_enabled is true (use num_node_groups / replicas_per_node_group instead)."
  default     = 2
}

variable "cluster_mode_enabled" {
  type        = bool
  description = "Enable Redis cluster mode (sharding). False by default: CacheOF and CacheOD are single-shard caches for adapter responses, no need to partition the keyspace."
  default     = false
}

variable "num_node_groups" {
  type        = number
  description = "Number of shards when cluster_mode_enabled is true. Ignored otherwise."
  default     = 1
}

variable "replicas_per_node_group" {
  type        = number
  description = "Replicas per shard when cluster_mode_enabled is true. Ignored otherwise."
  default     = 1
}

variable "engine_version" {
  type        = string
  description = "Redis engine version."
  default     = "7.1"
}

variable "automatic_failover_enabled" {
  type        = bool
  description = "Enable automatic failover to a replica if the primary node fails."
  default     = true
}

variable "multi_az_enabled" {
  type        = bool
  description = "Enable Multi-AZ for the replication group."
  default     = true
}

variable "kms_key_id" {
  type        = string
  description = "ARN of the CMK used for at-rest encryption."
}

variable "auth_token" {
  type        = string
  description = "Redis AUTH token (requires transit_encryption_enabled). If left empty, a random token is generated by the module."
  default     = ""
  sensitive   = true
}

variable "parameters" {
  type        = map(string)
  description = "Extra Redis parameters merged into the parameter group (parameter name -> value), e.g. { maxmemory-policy = \"allkeys-lru\" }."
  default     = {}
}

variable "snapshot_retention_limit" {
  type        = number
  description = "Number of days to retain automatic snapshots. 0 disables snapshots, which is the default for this destructible environment (HU-78)."
  default     = 0
}

variable "port" {
  type        = number
  description = "Port the cache clusters listen on."
  default     = 6379
}

variable "tags" {
  type        = map(string)
  description = "Extra tags merged into all taggable resources."
  default     = {}
}
