apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservicio.fullname" . }}
  labels:
    {{- include "microservicio.labels" . | nindent 4 }}
  {{- if .Values.prometheus.scrape }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.prometheus.path | quote }}
    prometheus.io/port: {{ .Values.puertoMetricas | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "microservicio.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.puerto }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.puertoMetricas }}
      targetPort: metrics
      protocol: TCP
